# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  #
  # Check for minor/patch versions only on a weekly basis - we are likely to be able to 
  # merge these routinely.
  #
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
        
  #
  # Check for all dependencies monthly including major (which are likely / prone to breaking changes.
  #
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    allow:
        update-types: ["version-update:semver-major"]
